vezetéknév = input('Mi a keresztneved?')
keresztnév = input('Mi a vezetékneved?')
év = input('Melyik évben születtél?')
csillagjegy = input('Melyik csillagjegyben születtél?')
print('A te neved ', vezetéknév, ' ', keresztnév, '.', sep='')
print('Az Úr ' , év, '. évében születtél, a ', csillagjegy, 'jegyében.', sep='')